### ISSUE TITLE
Qui écrit quoi ?

### ISSUE THREAD

**Issue by rougier** [rougier/URFIST-Book#1]

**Comment by nfrerebeau** [comment]
Chapitre 3

**Comment by nmonot** [comment]
Chapitre 5

**Comment by mariewach** [comment]
Chapitre 1

**Comment by SoufianeAjana** [comment]
Conclusion

**Comment by davidcarayon** [comment]
Chapitre 6 !

**Comment by anthonybtl** [comment]
Chapitre 11

**Comment by VinceZars** [comment]
Chapitre 2 :)

**Comment by kzrikem** [comment]
chapitre 8

**Comment by ogodumodu** [comment]
chapitre 7

**Comment by JeanBenenzech** [comment]
couverture

**Comment by artorig** [comment]
Chapitre 4

**Comment by sandrinep33** [comment]
Le titre

**Comment by MarKvaki** [comment]
Chapitre 13

**Comment by Grenouillerose** [comment]
les annexes

**Comment by rboisgard** [comment]
L'index

**Comment by rougier** [comment]
@JeanBenenzech Couverture
@rboisgard Index
@mariewach Chapitre 1
@VinceZars Chapitre 2
@nfrerebeau Chapitre 3
@artorig Chapitre 4
@nmonot  Chapitre 5
@davidcarayon Chapitre 6
@ogodumodu Chapitre 7
@kzrikem Chapitre 8
@anthonybtl Chapitre 9
@MarKvaki Chapitre 10
@sandrinep33 Conclusion
@Grenouillerose Annexes

😄
