### ISSUE TITLE
Qui écrit quoi ?

### ISSUE THREAD

**Issue by rougier** [rougier/URFIST-Book#29]
Voir le fichier [index.txt](https://github.com/rougier/URFIST-Book/blob/master/index.txt) pour voir ce qu'il faut écrire.

**Comment by stephane-chevalier** [comment]
chapitre 1

**Comment by JulietteArchambeau** [comment]
Préface

**Comment by nomisgor** [comment]
Je veux absolument faire le chapitre 7 !

**Comment by cammiermon** [comment]
Chapitre 2!

**Comment by frederic-santos** [comment]
Je prends le chapitre 5 !

**Comment by NPillaud** [comment]
Je veux bien écrire le chapitre 3.

**Comment by arlheureux** [comment]
Je me lance sur la conclusion

**Comment by JulietteArchambeau** [comment]
Je suis ultra motivée pour écrire la préface :D

**Comment by belloum** [comment]
Je veux le Chapitre 10 !!

**Comment by laumond** [comment]
50€ sur l'introduction

**Comment by El-Hassane** [comment]
je peux me positionner sur le Chap 6

**Comment by Sov02** [comment]
Chapitre 8 !

**Comment by nomisgor** [comment]
(Il parle de quoi le livre ?)

**Comment by cammiermon** [comment]
Bonne question tient ...

**Comment by mario-alcocer** [comment]
Pour moi le chap 4

**Comment by rougier** [comment]
Pour résumer:

* [ ] préface:  @JulietteArchambeau 
* [ ] introduction: @laumond 
* [ ] chaptire 1: @stephane-chevalier 
* [ ] chapitre 2: @cammiermon 
* [ ] chapitre 3: @NPillaud 
* [ ] chapitre 4: @mario-alcocer
* [ ] chapitre 5: @frederic-santos 
* [ ] chapitre 6: @El-Hassane 
* [ ] chapitre 7: @nomisgor 
* [ ] chapitre 8: @Sov02 
* [ ] chapitre 9: 
* [ ] chapitre 10: @belloum 
* [ ] conclusion:

**Comment by schisell** [comment]
Je voudrais ecrire le chapitre 9.
